### PR TITLE
cost: include currency in cost calculations 

### PR DESCRIPTION
**Pull request by theskch**
This PR resolves the issue #48 . It adds currency in cost and checks if the currency is the same when making calculations. Currency is extracted from the ingested data - from the database.

### CODE REVIEW

**Review by xescugc — COMMENTED** [review]
LGTM just one comment.

Also, I was thinking that for the currency we may need to `ToLower|ToUpper` so we always have the same format because between providers it may change, this made me think also in https://pkg.go.dev/golang.org/x/text/currency but IDK if it's worth using it as it can fail if invalid (https://pkg.go.dev/golang.org/x/text/currency#ParseISO) but I can assume the CP have valid info

**Comment by theskch** [comment]
IMHO using the https://pkg.go.dev/golang.org/x/text/currency#ParseISO is a good suggestion, I would expect all CP to have a valid currency format, and setting currencies for all CP to the same format before inserting them in the DB will guarantee there is no mismatch because of the format.

**Review by xescugc — COMMENTED** [review]
rs

**Comment by theskch** [comment]
RS Done

**Review by xescugc — APPROVED** [review]

**Pull request merged**
